remote_theme: alexcarpenter/material-jekyll-theme@1.0.0
plugins:
- jekyll-remote-theme

title: DangoPlayer Uni
logo: DangoPlayerUni_Logo.png

fixedNav: 'true'
themeColor: purple
sass:
  style: compressed
