remote_theme: brunochanrio/material-jekyll-chanrio@2025.04.14_v2
plugins:
- jekyll-remote-theme

title: DangoPlayer
description: A fast video player and IPTV client for Android and TV
author: Bruno-chanrio
logo: assets/DangoPlayerUni_Logo.png
mobilelogo: assets/DangoPlayerUni_Icon.png
socialcover: assets/DangoPlayerUni_AndroidTV_Banner.png
keywords: "DangoPlayer, Dango Player, IPTV Client, Video Player, IPTV Client for Android, Video Player for Android, IPTV, ExoPlayer, Media3, AndroidX, Android, Android TV, Google TV"



baseurl: "/DangoPlayer"
color: "#8CDEAD"
head-theme-color: "#A1008F"
accentColor: pink
themeColor: pink
fixedNav: 'true' # true or false
developedby: true

repo: "https://github.com/brunochanrio/DangoPlayer"
github_user: "brunochanrio"
github_repo: "DangoPlayer"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
