remote_theme: vsoch/mkdocs-jekyll@v0.0.12
plugins:
- jekyll-remote-theme

title: DangoPlayer Uni
logo: DangoPlayerUni_Logo.png



baseurl: "/DangoPlayer"
fixedNav: 'false'
accentColor: purple
themeColor: purple
sass:
  style: compressed

  permalink: /DangoPlayer/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]
