remote_theme: vsoch/mkdocs-jekyll@v0.0.12
plugins:
- jekyll-remote-theme

title: DangoPlayer
logo: DangoPlayerUni_Logo.png
logo_width: 40



baseurl: "/DangoPlayer"
color: "#2B0052"
accentColor: pink
themeColor: deep-purple
fixedNav: 'false' # true or false

repo: "https://github.com/brunochanrio/DangoPlayer"
github_user: "brunochanrio"
github_repo: "DangoPlayer"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
