remote_theme: brunochanrio/material-jekyll-chanrio@2025.03.24
plugins:
- jekyll-remote-theme

title: DangoPlayer
author: Bruno-chanrio
logo: assets/DangoPlayerUni_Logo.png
mobilelogo: assets/DangoPlayerUni_Icon.png



baseurl: "/DangoPlayer"
color: "#FF7FAC"
accentColor: pink
themeColor: pink
fixedNav: 'true' # true or false
developedby: true

repo: "https://github.com/brunochanrio/DangoPlayer"
github_user: "brunochanrio"
github_repo: "DangoPlayer"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
